include:
  - package:very_good_analysis/analysis_options.10.0.0.yaml
  - dcm_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'build/**'
    - 'native/**'

  errors:
    invalid_annotation_target: error

linter:
  rules:
    public_member_api_docs: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
