name: dart_monty_bridge
description: High-level bridge layer for dart_monty. Host functions, event loop, plugin system.
version: 0.3.1
homepage: https://github.com/runyaga/dart_monty
repository: https://github.com/runyaga/dart_monty
issue_tracker: https://github.com/runyaga/dart_monty/issues
topics:
  - python
  - sandbox
  - interpreter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_monty_platform_interface: ^0.7.0
  meta: ^1.11.0
  struct_log: ^0.1.0

dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^10.0.0
