#!/usr/bin/env bash
# =============================================================================
# DCM ratchet — fail on any NEW issue above the recorded baseline
# =============================================================================
# `dcm analyze` has been chronically red, which makes it
# useless as an upgrade gate: 5 new issues move the count 9 -> 14 and nobody
# notices, and *fixing* 10 old issues masks new ones behind a net improvement.
#
# This ratchets instead: any new rule, any per-rule increase, or any new file
# with issues fails. Reducing counts is always allowed and never required.
#
# Usage: bash tool/dcm_ratchet.sh [path/to/baseline.json]
# Baseline default: tool/dcm-baseline.json  (regenerate with --update)
# =============================================================================
set -uo pipefail

cd "$(git rev-parse --show-toplevel)"
BASELINE="${1:-tool/dcm-baseline.json}"
if [ "${1:-}" = "--update" ]; then BASELINE=tool/dcm-baseline.json; UPDATE=1; else UPDATE=0; fi

# A gate that silently skips is not a gate. Skipping is allowed ONLY when the
# caller opts in explicitly (local runs on a machine without dcm); anywhere the
# ratchet is relied upon — CI above all — a missing dcm must FAIL, because the
# alternative is a green tick that checked nothing.
if ! command -v dcm >/dev/null 2>&1; then
  if [ "${DCM_RATCHET_ALLOW_MISSING:-0}" = "1" ]; then
    echo "dcm not installed — SKIPPING (DCM_RATCHET_ALLOW_MISSING=1)"
    exit 77
  fi
  echo "FAIL: dcm is not installed, so the ratchet cannot run."
  echo "  Install:  brew tap CQLabs/dcm && brew install dcm"
  echo "  Note dcm is NOT a pub package — 'dart pub global activate dcm' does"
  echo "  not work. To skip deliberately on a machine without it:"
  echo "    DCM_RATCHET_ALLOW_MISSING=1 bash tool/dcm_ratchet.sh"
  exit 1
fi

# The baseline is only meaningful against the dcm that produced it: a different
# version reports different things, so a cross-version comparison compares two
# different measurements and reports noise as signal. This is not hypothetical
# here -- on the 1.37.0 -> 1.39.0 upgrade `dcm analyze` held at 9, but the
# sibling suite ratchet moved (check-dependencies 6 -> 5,
# check-unnecessarily-public-code 150 -> 151) at an unchanged grand total. The 9
# holding was luck, and luck is not a guard.
#
# `--update` is EXEMPT, or the pin deadlocks: the mismatch message says
# regenerate, and regeneration is what would be refused.
HAVE_V=$(dcm --version 2>&1 | tr -d '\r' | awk '{print $NF}')
WANT_V=$(python3 -c "import json;print(json.load(open('tool/dcm-baseline.json')).get('_dcm_version',''))" 2>/dev/null)
if [ "$UPDATE" = "0" ] && [ -n "$WANT_V" ] && [ "$HAVE_V" != "$WANT_V" ]; then
  echo "FAIL: dcm version mismatch — baseline was generated by $WANT_V, this is $HAVE_V."
  echo "  Counts are not comparable across versions. Install $WANT_V, or bump and"
  echo "  regenerate in the same commit: bash tool/dcm_ratchet.sh --update"
  exit 1
fi

# DCM IS COMMERCIAL, and 1.39.0 refuses outright where 1.37.0 ran a free tier:
# `dcm analyze lib --reporter=json` printed "DCM is not activated" and no JSON,
# so this script died on a bare json.decoder.JSONDecodeError with the reason
# thrown away by `2>/dev/null`. Measured on the 1.37.0 -> 1.39.0 upgrade.
#
# dcm only consults the credentials when it believes it is on CI, so CI=true is
# set ALONGSIDE them, not instead of them.
# LOCAL ACTIVATION IS THE PRIMARY PATH; CI CREDENTIALS ARE THE FALLBACK.
#
# `dcm activate --license-key=...` registers a SEAT on this machine, and an
# activated dcm needs no CI key, no email and no CI=true. The GitHub CI path is
# not supported by this project, so demanding those credentials refused the only
# path that is. Measured 2026-09-17 on an activated host, with DCM_CI_KEY,
# DCM_EMAIL and CI all explicitly unset: this script exited 1 while
# `dcm analyze lib --reporter=json` ran normally.
#
# Order matters: the CI key carries a MONTHLY RUN BUDGET and dies with "CI key
# limit for this month has been exceeded"; a seat does not. Preferring the seat
# spends the budget only when there is no seat.
#
# Ported from dart_monty_core 2e03bc2, where the same guard blocked the same
# path.
dcm_activated() { dcm license 2>/dev/null | grep -q '^DCM License:'; }

if ! dcm_activated && { [ -z "${DCM_CI_KEY:-}" ] || [ -z "${DCM_EMAIL:-}" ]; }; then
  if [ "${DCM_RATCHET_ALLOW_MISSING:-0}" = "1" ]; then
    echo "DCM credentials absent — SKIPPING (DCM_RATCHET_ALLOW_MISSING=1)"
    exit 77
  fi
  echo "FAIL: dcm is not activated here and no CI credentials are set."
  echo "  PREFERRED — activate a seat on this machine:"
  echo "    dcm activate --license-key=\$DCM_KEY   # DCM_KEY lives in ~/dev/.env"
  echo "    export DCM_CI_KEY=...   # the CI key, NOT a license-key"
  echo "    export DCM_EMAIL=...    # the purchase email"
  echo "  To run the gate without a licence, skipping this deliberately:"
  echo "    DCM_ALLOW_MISSING=1 bash tool/gate.sh"
  exit 1
fi

TMP=$(mktemp)
ERR=$(mktemp)
# stderr is CAPTURED, not discarded. A gate that hides why it failed is barely
# better than one that cannot fail -- this script previously surfaced a licence
# error as a Python traceback about column 1 of an empty file.
DCM_ENV=(); DCM_AUTH=()
if [ -n "${DCM_CI_KEY:-}" ] && [ -n "${DCM_EMAIL:-}" ]; then
  DCM_ENV=(env CI=true)
  DCM_AUTH=(--ci-key="$DCM_CI_KEY" --email="$DCM_EMAIL")
fi
"${DCM_ENV[@]}" dcm analyze lib --reporter=json "${DCM_AUTH[@]}" > "$TMP" 2>"$ERR"
DCM_RC=$?

if [ ! -s "$TMP" ] || ! python3 -c "import json,sys;json.load(open(sys.argv[1]))" "$TMP" 2>/dev/null; then
  echo "FAIL: \`dcm analyze --reporter=json\` produced no parseable JSON (exit $DCM_RC)."
  echo "  This is the gate failing to RUN, which is not the same as it passing."
  echo "  dcm version: $(dcm --version 2>&1 | head -1)"
  echo "  --- first 10 lines of stderr ---"
  head -10 "$ERR" | sed 's/^/    /'
  rm -f "$TMP" "$ERR"
  exit 1
fi
rm -f "$ERR"

BASELINE="$BASELINE" UPDATE="$UPDATE" TMP="$TMP" HAVE_V="$HAVE_V" python3 - <<'PY'
import json, os, sys, collections

tmp = os.environ['TMP']
baseline_path = os.environ['BASELINE']
update = os.environ['UPDATE'] == '1'

d = json.load(open(tmp))
rules, files = collections.Counter(), collections.Counter()
for r in d['analyzeResults']:
    for iss in r.get('issues', []):
        rules[iss['id']] += 1
        files[r['path']] += 1
current = {'total': sum(rules.values()), 'by_rule': dict(rules), 'by_file': dict(files)}

if update:
    current['_dcm_version'] = os.environ.get('HAVE_V', '')
    json.dump(current, open(baseline_path, 'w'), indent=2, sort_keys=True)
    print(f"baseline updated: {current['total']} issues, {len(rules)} rules, {len(files)} files")
    sys.exit(0)

if not os.path.exists(baseline_path):
    print(f"FAIL: no baseline at {baseline_path} — run: bash tool/dcm_ratchet.sh --update")
    sys.exit(1)

base = json.load(open(baseline_path))
bt, br, bf = base['total'], base['by_rule'], base['by_file']
violations = []

for rule, n in sorted(rules.items()):
    prev = br.get(rule, 0)
    if prev == 0:
        violations.append(f"NEW RULE      {rule}: {n} issue(s)")
    elif n > prev:
        violations.append(f"RULE INCREASE {rule}: {prev} -> {n}")

for path, n in sorted(files.items()):
    prev = bf.get(path, 0)
    if prev == 0:
        violations.append(f"NEW FILE      {path}: {n} issue(s)")
    elif n > prev:
        violations.append(f"FILE INCREASE {path}: {prev} -> {n}")

print(f"dcm: {current['total']} issues vs baseline {bt}  "
      f"({len(rules)} rules / {len(files)} files vs {len(br)} / {len(bf)})")

if violations:
    print(f"\nFAIL — {len(violations)} ratchet violation(s):")
    for v in violations:
        print(f"  {v}")
    print("\nFix them, or if intentional: bash tool/dcm_ratchet.sh --update")
    sys.exit(1)

if current['total'] < bt:
    print(f"PASS — and {bt - current['total']} fewer than baseline. "
          f"Consider: bash tool/dcm_ratchet.sh --update")
else:
    print("PASS — no new issues above baseline")
PY
rc=$?
rm -f "$TMP"
exit $rc
