#!/usr/bin/env bash
# =============================================================================
# DCM host gate — runs both DCM ratchets OUTSIDE the container, on dcm 1.39.0
# =============================================================================
# WHY OUTSIDE. `tool/gate.sh` is normally run inside the `dmc-build` container,
# which ships dcm **1.37.0**. Both baselines here were generated by **1.39.0**,
# which is the version this project standardises on. `dcm_ratchet.sh` pins the
# version deliberately -- counts are not comparable across dcm releases -- so
# the in-container run could only ever produce:
#
#     FAIL: dcm version mismatch — baseline was generated by 1.39.0, this is 1.37.0.
#
# Measured 2026-09-16 on integration/0.23: that was the ONLY failing check in an
# otherwise 10-pass gate. A gate that fails for a reason unrelated to the code
# gets ignored, and then deleted. The checks move to the host, and gate.sh skips
# them when it detects a container -- VISIBLY, as a skip, never as a pass.
#
# WHY AN ISOLATED WORKTREE, and not just `cd` to the repo. The container and the
# host cannot share one `.dart_tool/package_config.json`: the container resolves
# to `/home/.pub-cache/...`, which does not exist on macOS. Pointing host dcm at
# the live tree would analyse against a broken package config and report
# meaningless numbers. The damage is bidirectional -- a host `dart pub get` on
# the live tree rewrites that file to host paths and breaks the CONTAINER gate.
# (Measured this session: running host `dart pub get` in a checkout did exactly
# that.) A throwaway detached worktree avoids the thrash in both directions.
#
# Usage:
#   bash tool/dcm_host_gate.sh            # run both ratchets
#   bash tool/dcm_host_gate.sh --update   # regenerate baselines, copy them back
# =============================================================================
set -uo pipefail

if [ -e /run/.containerenv ] || [ -e /.dockerenv ]; then
  echo "FAIL: this script must run on the HOST, not inside the container."
  echo "  The container has dcm 1.37.0 and resolves packages to /home/.pub-cache,"
  echo "  which does not exist on the host. Run it from macOS:"
  echo "    bash tool/dcm_host_gate.sh"
  exit 1
fi

REPO="$(git rev-parse --show-toplevel)"
cd "$REPO" || exit 1
UPDATE=0
[ "${1:-}" = "--update" ] && UPDATE=1

WANT_DCM=1.39.0
if ! command -v dcm >/dev/null 2>&1; then
  echo "FAIL: dcm is not on the host PATH."
  echo "  brew trust --formula cqlabs/dcm/dcm && brew install cqlabs/dcm/dcm@$WANT_DCM"
  exit 1
fi
HAVE_DCM=$(dcm --version 2>&1 | tr -d '\r' | awk '{print $NF}')
if [ "$HAVE_DCM" != "$WANT_DCM" ]; then
  echo "FAIL: host dcm is $HAVE_DCM, this project standardises on $WANT_DCM."
  echo "  brew link --overwrite cqlabs/dcm/dcm@$WANT_DCM"
  exit 1
fi

# DCM IS COMMERCIAL AND THE LICENCE CAN FAIL FOR REASONS THAT ARE NOT "ABSENT".
# Measured 2026-09-16 with a valid key: "Failed to verify DCM license. Bad
# state: CI key limit for this month has been exceeded." Say so up front rather
# than letting each ratchet rediscover it.
if [ -z "${DCM_CI_KEY:-}" ] || [ -z "${DCM_EMAIL:-}" ]; then
  echo "NOTE: DCM_CI_KEY / DCM_EMAIL are not both set."
  echo "  The ratchets will report that themselves; this is not a pass."
fi

WT="${DCM_HOST_WORKTREE:-${TMPDIR:-/tmp}/dcm-host-$(basename "$REPO")}"
cleanup() {
  [ "${DCM_HOST_KEEP:-0}" = "1" ] && return 0
  git -C "$REPO" worktree remove --force "$WT" >/dev/null 2>&1
  git -C "$REPO" worktree prune >/dev/null 2>&1
}
# PIPE IS IN THE LIST DELIBERATELY: reading a gate's output through `head` or
# `tail` is the normal thing to do, and a trap on EXIT/INT/TERM alone does not
# fire for SIGPIPE -- which would leave the worktree behind.
trap cleanup EXIT INT TERM PIPE

git -C "$REPO" worktree remove --force "$WT" >/dev/null 2>&1
git -C "$REPO" worktree prune >/dev/null 2>&1
git worktree add --detach "$WT" HEAD >/dev/null 2>&1 || {
  echo "FAIL: could not create the analysis worktree at $WT"; exit 1; }

echo "worktree: $WT  (detached at $(git rev-parse --short HEAD))"
if ! (cd "$WT" && dart pub get >/dev/null 2>&1); then
  echo "FAIL: host \`dart pub get\` failed in the worktree."
  echo "  Without host-resolved dependencies every dcm result is meaningless."
  exit 1
fi

RC=0
run() {
  local label="$1"; shift
  echo "--- $label"
  if (cd "$WT" && "$@"); then echo "    PASS"; else
    local rc=$?
    if [ $rc -eq 77 ]; then echo "    SKIP (checked nothing)"; else echo "    FAIL"; RC=1; fi
  fi
}

if [ "$UPDATE" = "1" ]; then
  run "dcm analyze baseline" bash tool/dcm_ratchet.sh --update
  run "dcm suite baseline"   bash tool/dcm_suite_ratchet.sh --update
  # `--update` writes inside the WORKTREE. Copy the results back, or the
  # regeneration is thrown away with the worktree and the next run reports the
  # same mismatch for ever.
  for b in tool/dcm-baseline.json tool/dcm-suite-baseline.json; do
    if [ -f "$WT/$b" ] && ! cmp -s "$WT/$b" "$REPO/$b"; then
      cp "$WT/$b" "$REPO/$b"; echo "    updated $b in the real repo"
    fi
  done
else
  run "dcm analyze ratchet" bash tool/dcm_ratchet.sh
  run "dcm suite ratchet"   bash tool/dcm_suite_ratchet.sh
fi

[ $RC -eq 0 ] && echo "DCM HOST GATE GREEN" || echo "DCM HOST GATE RED"
exit $RC
