name: DCM

on:
  push:
    branches: [main]
    paths:
      - 'packages/**/*.dart'
      - 'example/**/*.dart'
  pull_request:
    branches: [main, 'feat/**']
    paths:
      - 'packages/**/*.dart'
      - 'example/**/*.dart'
  workflow_dispatch:

concurrency:
  group: dcm-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dcm:
    name: DCM
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - uses: CQLabs/setup-dcm@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: DCM analyze
        run: >-
          dcm analyze packages
          --ci-key=${{ secrets.DCM_CI_KEY }}
          --email=${{ secrets.DCM_EMAIL }}
          --fatal-found
